apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/shashank-ganesha/nginx-gitops.git
  branch: main
  secretRef:
    name: flux-system
